services:
  mail:
    class: AppBundle\Mailer\Mailer
    arguments:
      - "@mailer"
      - "@templating"
      - "@em"
      - %mailer_sender%

  twig.extension.string_loader:
    class: Twig_Extension_StringLoader
    tags:
     - { name: twig.extension }
